/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nanta
 */
public class project extends javax.swing.JFrame {

    /**
     * Creates new form project
     */
    public project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nilai = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Mapel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nilai");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 180, 110, 14);
        getContentPane().add(Nilai);
        Nilai.setBounds(250, 170, 170, 30);
        getContentPane().add(Nama);
        Nama.setBounds(250, 50, 170, 30);
        getContentPane().add(Absen);
        Absen.setBounds(250, 90, 170, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(250, 90, 170, 30);
        getContentPane().add(Mapel);
        Mapel.setBounds(250, 130, 170, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 60, 100, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 100, 110, 14);

        jLabel4.setText("Mapel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 140, 100, 14);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(20, 210, 65, 23);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 220, 290, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        int absen = Integer.parseInt(Absen.getText());
        String mapel = Mapel.getText();
        int nilai = Integer.parseInt(Nilai.getText());
        
        
        if(nilai<=74 && nilai>=0){
        Hasil.append("Nama Siswa : "+nama+"\n"+"Absen : "+absen+"\n"+"Mapel : "+mapel+"\n"+"Nilai anda :"+nilai+"\n"+"Predikat : "+"Maaf anda belum LULUS");
    }
    else if(nilai>=75 && nilai<=85){
        Hasil.append("Nama Siswa : "+nama+"\n"+"Absen : "+absen+"\n"+"Mapel : "+mapel+"\n"+"Nilai anda :"+nilai+"\n"+"Predikat : "+"Selamat, anda LULUS");
    }
    else if (nilai>85 && nilai<=100){
        Hasil.append("Nama Siswa : "+nama+"\n"+"Absen : "+absen+"\n"+"Mapel : "+mapel+"\n"+"Nilai anda :"+nilai+"\n"+"Predikat "+"Nilai anda sangat baik, anda LULUS");
    }
    else {
        Hasil.append("Nama Siswa : "+nama+"\n"+"Absen : "+absen+"\n"+"Mapel : "+mapel+"\n"+"Nilai anda :"+nilai+"\n"+"Predikat : "+"Nilai yang anda masukkan tidak valid");
    }
    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField Mapel;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai;
    private javax.swing.JButton Proses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
